version: '3'
services:
  web:
    build: .
    ports:
      - "8000:5000"
  mongodb:
    image: mongo
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=esiee
      - MONGODB_INITDB_ROOT_PASSWORD=paris
    volumes:
      - type: bind
        source: ./data
        target: /data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: esiee
      ME_CONFIG_MONGODB_ADMINPASSWORD: paris
      ME_CONFIG_MONGODB_URL: mongodb://esiee:paris@mongodb:27017/